<?php

return array(
    //ADMIN hat kein Primärschlüssel
    'SELECT_ALL_ADMIN' => 'SELECT * FROM ADMIN',

    'SELECT_ADRESSE_BY_ID' => 'SELECT * FROM ADRESSE WHERE idAdresse = ?',
    'SELECT_ALL_ADRESSE' => 'SELECT * FROM ADRESSE',

    'SELECT_BESTELLSTATUS_BY_ID' => 'SELECT * FROM BESTELLSTATUS WHERE idBestellstatus = ?',
    'SELECT_ALL_BESTELLSTATUS' => 'SELECT * FROM BESTELLSTATUS',

    'SELECT_BESTELLUNG_BY_ID' => 'SELECT * FROM BESTELLUNG WHERE idBestellung = ?',
    'SELECT_ALL_BESTELLUNG' => 'SELECT * FROM BESTELLUNG',

    'SELECT_CONTEST_BY_ID' => 'SELECT * FROM CONTEST WHERE idContest = ?',
    'SELECT_ALL_CONTEST' => 'SELECT * FROM CONTEST',

    'SELECT_ENERGIEWERT_BY_ID' => 'SELECT * FROM ENERGIEWERT WHERE idEnergiewert = ?',
    'SELECT_ALL_ENERGIEWERT' => 'SELECT * FROM ENERGIEWERT',

    'SELECT_ICON_BY_ID' => 'SELECT * FROM ICON WHERE idIcon = ?',
    'SELECT_ALL_ICON' => 'SELECT * FROM ICON',

    'SELECT_KUNDE_BY_ID' => 'SELECT * FROM KUNDE WHERE idKunde = ?',
    'SELECT_ALL_KUNDE' => 'SELECT * FROM KUNDE',

    'SELECT_LADESPRUECHE_BY_ID' => 'SELECT * FROM LADESPRUECHE WHERE idLadesprueche = ?',
    'SELECT_ALL_LADESPRUECHE' => 'SELECT * FROM LADESPRUECHE',

    'SELECT_LOGIN_BY_ID' => 'SELECT * FROM LOGIN WHERE idLogin = ?',
    'SELECT_ALL_LOGIN' => 'SELECT * FROM LOGIN',

    'SELECT_MENUE_BY_ID' => 'SELECT * FROM MENUE WHERE idMenue = ?',
    'SELECT_ALL_MENUE' => 'SELECT * FROM MENUE',

    'SELECT_PRODUKT_BY_ID' => 'SELECT * FROM PRODUKT WHERE idProdukt = ?',
    'SELECT_ALL_PRODUKT' => 'SELECT * FROM PRODUKT',

    'SELECT_RABATT_BY_ID' => 'SELECT * FROM RABATT WHERE idRabatt = ?',
    'SELECT_ALL_RABATT' => 'SELECT * FROM RABATT',

    'SELECT_RATING_BY_ID' => 'SELECT * FROM RATING WHERE idRating = ?',
    'SELECT_ALL_RATING' => 'SELECT * FROM RATING',

    'SELECT_RECHNUNG_BY_ID' => 'SELECT * FROM RECHNUNG WHERE idRechnung = ?',
    'SELECT_ALL_RECHNUNG' => 'SELECT * FROM RECHNUNG',

    'SELECT_ZAHLUNGSART_BY_ID' => 'SELECT * FROM ZAHLUNGSART WHERE idZahlungsart = ?',
    'SELECT_ALL_ZAHLUNGSART' => 'SELECT * FROM ZAHLUNGSART',

    'SELECT_ZUTAT_BY_ID' => 'SELECT * FROM ZUTAT WHERE idZutat = ?',
    'SELECT_ALL_ZUTAT' => 'SELECT * FROM ZUTAT',

    'SELECT_ALL_MENUE_VON_PRODUKTID' => 'SELECT * FROM MENUE_PRODUKT JOIN MENUE ON Menue_idMenue = idMenue JOIN PRODUKT ON Produkt_idProdukt = idProdukt WHERE idProdukt = ?',
    'SELECT_ALL_PRODUKT_VON_MENUEID' => 'SELECT * FROM MENUE_PRODUKT JOIN MENUE ON Menue_idMenue = idMenue JOIN PRODUKT ON Produkt_idProdukt = idProdukt WHERE idMenue = ?',
    'SELECT_ALL_MENUE_PRODUKT' => 'SELECT * FROM MENUE_PRODUKT JOIN MENUE ON Menue_idMenue = idMenue JOIN PRODUKT ON Produkt_idProdukt = idProdukt',

    'SELECT_ALL_PRODUKT_VON_ZUTATID' => 'SELECT * FROM PRODUKT_ZUTAT JOIN PRODUKT ON Produkt_idProdukt = idProdukt JOIN ZUTAT ON Zutat_idZutat = idZutat WHERE idZutat = ?',
    'SELECT_ALL_ZUTAT_VON_PRODUKTID' => 'SELECT * FROM PRODUKT_ZUTAT JOIN PRODUKT ON Produkt_idProdukt = idProdukt JOIN ZUTAT ON Zutat_idZutat = idZutat WHERE idProdukt = ?',
    'SELECT_ALL_PRODUKT_UND_ZUTAT' => 'SELECT * FROM PRODUKT_ZUTAT JOIN PRODUKT ON Produkt_idProdukt = idProdukt JOIN ZUTAT ON Zutat_idZutat = idZutat',
);