-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 10:06:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fastFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastFood` DEFAULT CHARACTER SET utf8 ;
USE `fastFood` ;

-- -----------------------------------------------------
-- Table `fastFood`.`Icon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Icon` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Icon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BildPfad` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `idIcon_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Produkt` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Produkt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Icon_id` INT NOT NULL,
  `Titel` VARCHAR(255) NOT NULL,
  `Beschreibung` VARCHAR(255) NULL,
  `Preis` DECIMAL(10,2) NOT NULL,
  `Lagerbestand` INT NOT NULL,
  `Rabatt` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`, `Icon_id`),
  UNIQUE INDEX `idProdukt_UNIQUE` (`id` ASC),
  INDEX `fk_Produkt_Icon1_idx` (`Icon_id` ASC),
  CONSTRAINT `fk_Produkt_Icon1`
    FOREIGN KEY (`Icon_id`)
    REFERENCES `fastFood`.`Icon` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Strassenname` VARCHAR(255) NOT NULL,
  `Hausnummer` VARCHAR(10) NOT NULL,
  `Zusatz` VARCHAR(255) NULL,
  `PLZ` VARCHAR(10) NOT NULL,
  `Stadt` VARCHAR(255) NOT NULL,
  `Bundesland` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Login` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nutzername` VARCHAR(255) NOT NULL,
  `Passwort` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nutzername_UNIQUE` (`Nutzername` ASC),
  UNIQUE INDEX `idLogin_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Kunde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Kunde` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Kunde` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Adresse_id` INT NOT NULL,
  `Vorname` VARCHAR(255) NOT NULL,
  `Nachname` VARCHAR(255) NOT NULL,
  `Telefonnummer` VARCHAR(20) NULL,
  `Registrierungsdatum` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Login_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Adresse_id`, `Login_id`),
  INDEX `fk_Kunde_Adresse1_idx` (`Adresse_id` ASC),
  UNIQUE INDEX `idKunde_UNIQUE` (`id` ASC),
  INDEX `fk_Kunde_Login1_idx` (`Login_id` ASC),
  CONSTRAINT `fk_Kunde_Adresse1`
    FOREIGN KEY (`Adresse_id`)
    REFERENCES `fastFood`.`Adresse` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kunde_Login1`
    FOREIGN KEY (`Login_id`)
    REFERENCES `fastFood`.`Login` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Zahlungsart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Zahlungsart` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Zahlungsart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Art` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idRechnung_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Menue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Menue` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Menue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Titel` VARCHAR(255) NOT NULL,
  `Beschreibung` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idMenue_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Bestellstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Bestellstatus` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Bestellstatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idBestellstatus_UNIQUE` (`id` ASC),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Bestellung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Bestellung` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Bestellung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BestellungDatum` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Kunde_id` INT NOT NULL,
  `Zahlungsart_id` INT NOT NULL,
  `Produkt_id` INT NOT NULL,
  `Menue_id` INT NOT NULL,
  `Bestellstatus_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Kunde_id`, `Zahlungsart_id`, `Produkt_id`, `Menue_id`, `Bestellstatus_id`),
  UNIQUE INDEX `idBestellung_UNIQUE` (`id` ASC),
  INDEX `fk_Bestellung_Kunde1_idx` (`Kunde_id` ASC),
  INDEX `fk_Bestellung_Zahlungsart1_idx` (`Zahlungsart_id` ASC),
  INDEX `fk_Bestellung_Produkt1_idx` (`Produkt_id` ASC),
  INDEX `fk_Bestellung_Menue1_idx` (`Menue_id` ASC),
  INDEX `fk_Bestellung_Bestellstatus1_idx` (`Bestellstatus_id` ASC),
  CONSTRAINT `fk_Bestellung_Kunde1`
    FOREIGN KEY (`Kunde_id`)
    REFERENCES `fastFood`.`Kunde` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Zahlungsart1`
    FOREIGN KEY (`Zahlungsart_id`)
    REFERENCES `fastFood`.`Zahlungsart` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Produkt1`
    FOREIGN KEY (`Produkt_id`)
    REFERENCES `fastFood`.`Produkt` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Menue1`
    FOREIGN KEY (`Menue_id`)
    REFERENCES `fastFood`.`Menue` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_Bestellstatus1`
    FOREIGN KEY (`Bestellstatus_id`)
    REFERENCES `fastFood`.`Bestellstatus` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Rabatt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Rabatt` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Rabatt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `minderung` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idRabatt_UNIQUE` (`id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Rechnung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Rechnung` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Rechnung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Bestellung_id` INT NOT NULL,
  `ZahlungsDatum` DATETIME NOT NULL,
  `Rabatt_id` INT NULL,
  PRIMARY KEY (`id`, `Bestellung_id`, `Rabatt_id`),
  UNIQUE INDEX `idRechnung_UNIQUE` (`id` ASC),
  INDEX `fk_Rechnung_Bestellung1_idx` (`Bestellung_id` ASC),
  INDEX `fk_Rechnung_Rabatt1_idx` (`Rabatt_id` ASC),
  CONSTRAINT `fk_Rechnung_Bestellung1`
    FOREIGN KEY (`Bestellung_id`)
    REFERENCES `fastFood`.`Bestellung` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rechnung_Rabatt1`
    FOREIGN KEY (`Rabatt_id`)
    REFERENCES `fastFood`.`Rabatt` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Zutat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Zutat` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Zutat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ZutatName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idZutat_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Produkt_Zutat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Produkt_Zutat` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Produkt_Zutat` (
  `Produkt_id` INT NOT NULL AUTO_INCREMENT,
  `Zutat_id` INT NOT NULL,
  PRIMARY KEY (`Produkt_id`, `Zutat_id`),
  INDEX `fk_Produkt_Zutat_Zutat_idx` (`Zutat_id` ASC),
  INDEX `fk_Produkt_Zutat_Produkt1_idx` (`Produkt_id` ASC),
  CONSTRAINT `fk_Produkt_Zutat_Zutat`
    FOREIGN KEY (`Zutat_id`)
    REFERENCES `fastFood`.`Zutat` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produkt_Zutat_Produkt1`
    FOREIGN KEY (`Produkt_id`)
    REFERENCES `fastFood`.`Produkt` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Energiewert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Energiewert` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Energiewert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Produkt_id` INT NOT NULL,
  `PortionSize` VARCHAR(255) NULL,
  `Kalorien` DECIMAL(5,2) NULL,
  `Fett` DECIMAL(5,2) NULL,
  `Kohlenhydrate` DECIMAL(5,2) NULL,
  `Zucker` DECIMAL(5,2) NULL,
  `Eiweiss` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`, `Produkt_id`),
  UNIQUE INDEX `idRechnung_UNIQUE` (`id` ASC),
  INDEX `fk_Energiewert_Produkt1_idx` (`Produkt_id` ASC),
  CONSTRAINT `fk_Energiewert_Produkt1`
    FOREIGN KEY (`Produkt_id`)
    REFERENCES `fastFood`.`Produkt` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Menue_Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Menue_Produkt` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Menue_Produkt` (
  `Menue_id` INT NOT NULL,
  `Produkt_id` INT NOT NULL,
  PRIMARY KEY (`Menue_id`, `Produkt_id`),
  INDEX `fk_Menue_Produkt_Produkt1_idx` (`Produkt_id` ASC),
  CONSTRAINT `fk_Menue_Produkt_Menue1`
    FOREIGN KEY (`Menue_id`)
    REFERENCES `fastFood`.`Menue` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menue_Produkt_Produkt1`
    FOREIGN KEY (`Produkt_id`)
    REFERENCES `fastFood`.`Produkt` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Contest` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bild` BLOB NOT NULL,
  `Bestellung_id` INT NOT NULL,
  `freigeschalten` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Bestellung_id`),
  UNIQUE INDEX `idContest_UNIQUE` (`id` ASC),
  INDEX `fk_Contest_Bestellung1_idx` (`Bestellung_id` ASC),
  CONSTRAINT `fk_Contest_Bestellung1`
    FOREIGN KEY (`Bestellung_id`)
    REFERENCES `fastFood`.`Bestellung` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Rating` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Kunde_id` INT NOT NULL,
  `Contest_id` INT NOT NULL,
  `Rating` INT(5) NOT NULL,
  PRIMARY KEY (`id`, `Kunde_id`, `Contest_id`),
  UNIQUE INDEX `idRating_UNIQUE` (`id` ASC),
  INDEX `fk_Rating_Kunde1_idx` (`Kunde_id` ASC),
  INDEX `fk_Rating_Contest1_idx` (`Contest_id` ASC),
  CONSTRAINT `fk_Rating_Kunde1`
    FOREIGN KEY (`Kunde_id`)
    REFERENCES `fastFood`.`Kunde` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Contest1`
    FOREIGN KEY (`Contest_id`)
    REFERENCES `fastFood`.`Contest` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Admin` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Admin` (
  `Login_id` INT NOT NULL,
  PRIMARY KEY (`Login_id`),
  UNIQUE INDEX `Login_idLogin_UNIQUE` (`Login_id` ASC),
  CONSTRAINT `fk_Admin_Login1`
    FOREIGN KEY (`Login_id`)
    REFERENCES `fastFood`.`Login` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fastFood`.`Ladesprueche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastFood`.`Ladesprueche` ;

CREATE TABLE IF NOT EXISTS `fastFood`.`Ladesprueche` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `spruch` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idLadesprueche_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
